---
# reference https://github.com/coopnorge/cloud-platform-apis/blob/main/cloud-platform-apis/templates/repositoryconfig.github.coop.no/definition.yaml
# status of this repository: https://argocd.internal.coop/applications?search=pallet-renovate&showFavorites=false&proj=&sync=&autoSync=&health=&namespace=&cluster=&labels=
apiVersion: github.coop.no/v1alpha1
kind: RepositoryConfig
metadata:
  name: repository-config
spec:
  description: Reusable GitHub workflow for renovate bot
  actions:
    enableReusableWorkflowsForOrganizationAccess: true
  visibility: public
  branches:
    default: main
    protection:
    - id: main
      pattern: main
      requiredStatusChecks:
        checks:
        - "validate-ci-results"
        - "policy-bot: main"
